# Site settings
title: custer的学习记录
description: custer的学习记录
baseurl: "/custertian.github.io" # the subpath of your site, e.g. /blog
url: "http://custer.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Custer
user_description: Python Developer at Lorem Ipsum Dolor
user_title: 开发界的小学生
email: custertian@gmail.com
twitter_username: custer
github_username:  custertian
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
